"""phase6_complete_simulation_schema

Revision ID: 0a57adf29d6b
Revises: 84c199d58ab6
Create Date: 2026-09-10 14:49:24.370230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a57adf29d6b'
down_revision: Union[str, Sequence[str], None] = '84c199d58ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_events', sa.Column('severity', sa.String(length=50), nullable=True))
    op.add_column('shipment_events', sa.Column('metadata_json', sa.Text(), nullable=True))
    # Add with server_default so existing rows are back-filled before
    # we enforce NOT NULL in the subsequent alter_column call.
    op.add_column('shipments', sa.Column(
        'weather_scenario',
        sa.String(length=50),
        nullable=True,
        server_default='normal_day'
    ))
    op.add_column('shipments', sa.Column(
        'operational_scenario',
        sa.String(length=50),
        nullable=True,
        server_default='normal_day'
    ))
    op.execute("UPDATE shipments SET weather_scenario = 'normal_day' WHERE weather_scenario IS NULL")
    op.execute("UPDATE shipments SET operational_scenario = 'normal_day' WHERE operational_scenario IS NULL")
    op.alter_column('shipments', 'weather_scenario', nullable=False, server_default=None)
    op.alter_column('shipments', 'operational_scenario', nullable=False, server_default=None)
    op.add_column('simulation_events', sa.Column('weather', sa.String(length=50), nullable=True))
    op.add_column('simulation_events', sa.Column('congestion_level', sa.String(length=50), nullable=True))
    op.add_column('simulation_events', sa.Column('speed_modifier', sa.Float(), nullable=True))
    op.add_column('simulation_events', sa.Column('port_wait_hours', sa.Float(), nullable=True))
    op.drop_column('simulation_events', 'humidity')
    op.drop_column('simulation_events', 'waiting_time')
    op.drop_column('simulation_events', 'asset_utilization')
    op.drop_column('simulation_events', 'temperature')
    op.drop_column('simulation_events', 'traffic_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_events', sa.Column('traffic_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('simulation_events', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('simulation_events', sa.Column('asset_utilization', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('simulation_events', sa.Column('waiting_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('simulation_events', sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('simulation_events', 'port_wait_hours')
    op.drop_column('simulation_events', 'speed_modifier')
    op.drop_column('simulation_events', 'congestion_level')
    op.drop_column('simulation_events', 'weather')
    op.drop_column('shipments', 'operational_scenario')
    op.drop_column('shipments', 'weather_scenario')
    op.drop_column('shipment_events', 'metadata_json')
    op.drop_column('shipment_events', 'severity')
    # ### end Alembic commands ###
