"""create initial database schema

Revision ID: 456b876f374b
Revises: 
Create Date: 2026-09-03 18:09:34.703531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456b876f374b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carriers_code'), 'carriers', ['code'], unique=True)
    op.create_index(op.f('ix_carriers_id'), 'carriers', ['id'], unique=False)
    op.create_table('dependency_graph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_graph_id'), 'dependency_graph', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('route_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_code')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_reference', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('shipping_mode', sa.String(length=50), nullable=True),
    sa.Column('shipment_status', sa.String(length=50), nullable=True),
    sa.Column('customer_segment', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('order_region', sa.String(length=100), nullable=True),
    sa.Column('sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('profit_per_order', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('scheduled_shipping_days', sa.Integer(), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_reference'), 'shipments', ['shipment_reference'], unique=True)
    op.create_table('ai_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('delay_probability', sa.Float(), nullable=False),
    sa.Column('predicted_eta', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('prediction_time', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_id'), 'ai_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_predictions_prediction_time'), 'ai_predictions', ['prediction_time'], unique=False)
    op.create_index(op.f('ix_ai_predictions_shipment_id'), 'ai_predictions', ['shipment_id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected_delay_reduction', sa.Float(), nullable=True),
    sa.Column('expected_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_id'), 'ai_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_shipment_id'), 'ai_recommendations', ['shipment_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_shipment_id'), 'documents', ['shipment_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_shipment_id'), 'notifications', ['shipment_id'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_events_event_time'), 'shipment_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_shipment_events_id'), 'shipment_events', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_events_shipment_id'), 'shipment_events', ['shipment_id'], unique=False)
    op.create_table('simulation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('simulation_time', sa.DateTime(), nullable=False),
    sa.Column('traffic_status', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('waiting_time', sa.Float(), nullable=True),
    sa.Column('asset_utilization', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_events_id'), 'simulation_events', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_events_shipment_id'), 'simulation_events', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_simulation_events_simulation_time'), 'simulation_events', ['simulation_time'], unique=False)
    op.create_table('decision_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=100), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ai_recommendations.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_history_id'), 'decision_history', ['id'], unique=False)
    op.create_index(op.f('ix_decision_history_recommendation_id'), 'decision_history', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_decision_history_shipment_id'), 'decision_history', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_history_shipment_id'), table_name='decision_history')
    op.drop_index(op.f('ix_decision_history_recommendation_id'), table_name='decision_history')
    op.drop_index(op.f('ix_decision_history_id'), table_name='decision_history')
    op.drop_table('decision_history')
    op.drop_index(op.f('ix_simulation_events_simulation_time'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_shipment_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_id'), table_name='simulation_events')
    op.drop_table('simulation_events')
    op.drop_index(op.f('ix_shipment_events_shipment_id'), table_name='shipment_events')
    op.drop_index(op.f('ix_shipment_events_id'), table_name='shipment_events')
    op.drop_index(op.f('ix_shipment_events_event_time'), table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_index(op.f('ix_notifications_shipment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_documents_shipment_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_ai_recommendations_shipment_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_ai_predictions_shipment_id'), table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_predictions_prediction_time'), table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_predictions_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_shipments_shipment_reference'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_dependency_graph_id'), table_name='dependency_graph')
    op.drop_table('dependency_graph')
    op.drop_index(op.f('ix_carriers_id'), table_name='carriers')
    op.drop_index(op.f('ix_carriers_code'), table_name='carriers')
    op.drop_table('carriers')
    # ### end Alembic commands ###
