"""add simulation speed history fields

Revision ID: 9a5cff2debc3
Revises: 0a57adf29d6b
Create Date: 2026-09-11 20:52:52.335053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5cff2debc3'
down_revision: Union[str, Sequence[str], None] = '0a57adf29d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_events', sa.Column('effective_speed_kmh', sa.Float(), nullable=True))
    op.add_column('simulation_events', sa.Column('distance_remaining_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_events', 'distance_remaining_km')
    op.drop_column('simulation_events', 'effective_speed_kmh')
    # ### end Alembic commands ###
